export const ADD_COIN_PAIR = 'ADD_COIN_PAIR';
export const UPDATE_TICKER = 'UPDATE_TICKER';
export const REMOVE_COIN_PAIR = 'REMOVE_COIN_PAIR';
export const SET_DEFAULT_CURRENCY = 'SET_DEFAULT_CURRENCY';
